In [1]:
import numpy as np
# scipy.special for the sigmoid function expit()
import scipy.special as special

In [2]:
# neural network class definition
class NeuralNetwork:
    # initialize the neural network
    def __init__(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        self.i_nodes = input_nodes
        self.h_nodes = hidden_nodes
        self.o_nodes = output_nodes
        
        # learning rate
        self.lr = learning_rate
        
        # link weight matrices, wih and who
        # weights inside the arrays are w_i_j where link is from node i to node j in the next layer
        # w11 w21
        # w12 w22 etc
        self.wih = (np.random.rand(self.h_nodes, self.i_nodes) - 0.5)
        print("Weights for input to hidden:\n", self.wih)
        
        self.who = (np.random.rand(self.o_nodes, self.h_nodes) - 0.5)
        print("Weights for hidden to output:\n", self.who)
        
        # activation function is the sigmoid function
        self.activation_function = lambda x: special.expit(x)
        pass
    
    # train the neural network
    def train(self, input_list, target_list):
        # convert input list to 2d array
        inputs = np.array(input_list, ndmin=2).T
        print("Inputs:\n", inputs)
        
        targets = np.array(target_list, ndmin=2).T
        print("Targets:\n", targets)
        
        #calculate signals into hidden layer
        hidden_inputs = np.dot(self.wih, inputs)
        print("Hidden inputs:\n", hidden_inputs)
        
        # calculate signals emerging out from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        print("Hidden outputs:\n", hidden_outputs)
        
        # calculate signals into final output layer
        final_inputs = np.dot(self.who, hidden_outputs)
        print("Final iutputs:\n", final_inputs)
        
        # calculate signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        print("Final outputs:\n", final_outputs)
        
        # error is the (target - actual)
        output_errors = targets - final_outputs
        print("Output errors:\n", output_errors)
        
        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = np.dot(self.who.T, output_errors)
        print("Output errors:\n", hidden_errors)
        
        # update the weights for the links between the hidden and output layers
        self.who += self.lr * np.dot((output_errors * final_outputs * (1.0 - final_outputs)), np.transpose(hidden_outputs))
        
        # update the weights for the links between the input and hidden layers
        self.wih += self.lr * np.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), np.transpose(inputs))
    
    # query the neural network
    def query(self, input_list):
        # convert input list to 2d array
        inputs = np.array(input_list, ndmin=2).T
        print("Inputs:\n", inputs)
        
        # calculate signals into hidden layer
        hidden_inputs = np.dot(self.wih, inputs)
        print("Hidden inputs:\n", hidden_inputs)
        
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        print("Hidden outputs:\n", hidden_outputs)
        
        # calculate signals into final output layer
        final_inputs = np.dot(self.who, hidden_outputs)
        print("Final iutputs:\n", final_inputs)
        
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        print("Final outputs:\n", final_outputs)
        
        return final_outputs

In [3]:
# setting hyperparameters
input_nodes = 4
hidden_nodes = 4
output_nodes = 1
learning_rate = 0.5

In [4]:
n = NeuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)

Weights for input to hidden:
 [[ 0.21593294  0.0399007  -0.33019674 -0.49796576]
 [-0.4620482   0.13460708  0.38570512 -0.33340707]
 [-0.41807961 -0.15206087 -0.11853423  0.40620257]
 [ 0.16420135  0.47633862  0.10155547  0.01155774]]
Weights for hidden to output:
 [[-0.1124004   0.31301378 -0.37879145 -0.36247641]]


In [7]:
data = [[5.1, 3.5, 1.4, 0.2, 1],
[4.9, 3, 1.4, 0.2, 1],
[4.7, 3.2, 1.3, 0.2, 1],
[4.6, 3.1, 1.5, 0.2, 1],
[5, 3.6, 1.4, 0.2, 1],
[5.4, 3.9, 1.7, 0.4, 1],
[4.6, 3.4, 1.4, 0.3, 1],
[5, 3.4, 1.5, 0.2, 1],
[4.4, 2.9, 1.4, 0.2, 1],
[4.9, 3.1, 1.5, 0.1, 1],
[5.4, 3.7, 1.5, 0.2, 1],
[4.8, 3.4, 1.6, 0.2, 1],
[4.8, 3, 1.4, 0.1, 1],
[4.3, 3, 1.1, 0.1, 1],
[5.8, 4, 1.2, 0.2, 1],
[5.7, 4.4, 1.5, 0.4, 1],
[5.4, 3.9, 1.3, 0.4, 1],
[5.1, 3.5, 1.4, 0.3, 1],
[5.7, 3.8, 1.7, 0.3, 1],
[5.1, 3.8, 1.5, 0.3, 1],
[5.4, 3.4, 1.7, 0.2, 1],
[5.1, 3.7, 1.5, 0.4, 1],
[4.6, 3.6, 1, 0.2, 1],
[5.1, 3.3, 1.7, 0.5, 1],
[4.8, 3.4, 1.9, 0.2, 1],
[5, 3, 1.6, 0.2, 1],
[5, 3.4, 1.6, 0.4, 1],
[5.2, 3.5, 1.5, 0.2, 1],
[5.2, 3.4, 1.4, 0.2, 1],
[4.7, 3.2, 1.6, 0.2, 1],
[4.8, 3.1, 1.6, 0.2, 1],
[5.4, 3.4, 1.5, 0.4, 1],
[5.2, 4.1, 1.5, 0.1, 1],
[5.5, 4.2, 1.4, 0.2, 1],
[4.9, 3.1, 1.5, 0.1, 1],
[5, 3.2, 1.2, 0.2, 1],
[5.5, 3.5, 1.3, 0.2, 1],
[4.9, 3.1, 1.5, 0.1, 1],
[4.4, 3, 1.3, 0.2, 1],
[5.1, 3.4, 1.5, 0.2, 1],
[5, 3.5, 1.3, 0.3, 1],
[4.5, 2.3, 1.3, 0.3, 1],
[4.4, 3.2, 1.3, 0.2, 1],
[5, 3.5, 1.6, 0.6, 1],
[5.1, 3.8, 1.9, 0.4, 1],
[4.8, 3, 1.4, 0.3, 1],
[5.1, 3.8, 1.6, 0.2, 1],
[4.6, 3.2, 1.4, 0.2, 1],
[5.3, 3.7, 1.5, 0.2, 1],
[5, 3.3, 1.4, 0.2, 1],
[7, 3.2, 4.7, 1.4, 2],
[6.4, 3.2, 4.5, 1.5, 2],
[6.9, 3.1, 4.9, 1.5, 2],
[5.5, 2.3, 4, 1.3, 2],
[6.5, 2.8, 4.6, 1.5, 2],
[5.7, 2.8, 4.5, 1.3, 2],
[6.3, 3.3, 4.7, 1.6, 2],
[4.9, 2.4, 3.3, 1, 2],
[6.6, 2.9, 4.6, 1.3, 2],
[5.2, 2.7, 3.9, 1.4, 2],
[5, 2, 3.5, 1, 2],
[5.9, 3, 4.2, 1.5, 2],
[6, 2.2, 4, 1, 2],
[6.1, 2.9, 4.7, 1.4, 2],
[5.6, 2.9, 3.6, 1.3, 2],
[6.7, 3.1, 4.4, 1.4, 2],
[5.6, 3, 4.5, 1.5, 2],
[5.8, 2.7, 4.1, 1, 2],
[6.2, 2.2, 4.5, 1.5, 2],
[5.6, 2.5, 3.9, 1.1, 2],
[5.9, 3.2, 4.8, 1.8, 2],
[6.1, 2.8, 4, 1.3, 2],
[6.3, 2.5, 4.9, 1.5, 2],
[6.1, 2.8, 4.7, 1.2, 2],
[6.4, 2.9, 4.3, 1.3, 2],
[6.6, 3, 4.4, 1.4, 2],
[6.8, 2.8, 4.8, 1.4, 2],
[6.7, 3, 5, 1.7, 2],
[6, 2.9, 4.5, 1.5, 2],
[5.7, 2.6, 3.5, 1, 2],
[5.5, 2.4, 3.8, 1.1, 2],
[5.5, 2.4, 3.7, 1, 2],
[5.8, 2.7, 3.9, 1.2, 2],
[6, 2.7, 5.1, 1.6, 2],
[5.4, 3, 4.5, 1.5, 2],
[6, 3.4, 4.5, 1.6, 2],
[6.7, 3.1, 4.7, 1.5, 2],
[6.3, 2.3, 4.4, 1.3, 2],
[5.6, 3, 4.1, 1.3, 2],
[5.5, 2.5, 4, 1.3, 2],
[5.5, 2.6, 4.4, 1.2, 2],
[6.1, 3, 4.6, 1.4, 2],
[5.8, 2.6, 4, 1.2, 2],
[5, 2.3, 3.3, 1, 2],
[5.6, 2.7, 4.2, 1.3, 2],
[5.7, 3, 4.2, 1.2, 2],
[5.7, 2.9, 4.2, 1.3, 2],
[6.2, 2.9, 4.3, 1.3, 2],
[5.1, 2.5, 3, 1.1, 2],
[5.7, 2.8, 4.1, 1.3, 2],
[6.3, 3.3, 6, 2.5, 3],
[5.8, 2.7, 5.1, 1.9, 3],
[7.1, 3, 5.9, 2.1, 3],
[6.3, 2.9, 5.6, 1.8, 3],
[6.5, 3, 5.8, 2.2, 3],
[7.6, 3, 6.6, 2.1, 3],
[4.9, 2.5, 4.5, 1.7, 3],
[7.3, 2.9, 6.3, 1.8, 3],
[6.7, 2.5, 5.8, 1.8, 3],
[7.2, 3.6, 6.1, 2.5, 3],
[6.5, 3.2, 5.1, 2, 3],
[6.4, 2.7, 5.3, 1.9, 3],
[6.8, 3, 5.5, 2.1, 3],
[5.7, 2.5, 5, 2, 3],
[5.8, 2.8, 5.1, 2.4, 3],
[6.4, 3.2, 5.3, 2.3, 3],
[6.5, 3, 5.5, 1.8, 3],
[7.7, 3.8, 6.7, 2.2, 3],
[7.7, 2.6, 6.9, 2.3, 3],
[6, 2.2, 5, 1.5, 3],
[6.9, 3.2, 5.7, 2.3, 3],
[5.6, 2.8, 4.9, 2, 3],
[7.7, 2.8, 6.7, 2, 3],
[6.3, 2.7, 4.9, 1.8, 3],
[6.7, 3.3, 5.7, 2.1, 3],
[7.2, 3.2, 6, 1.8, 3],
[6.2, 2.8, 4.8, 1.8, 3],
[6.1, 3, 4.9, 1.8, 3],
[6.4, 2.8, 5.6, 2.1, 3],
[7.2, 3, 5.8, 1.6, 3],
[7.4, 2.8, 6.1, 1.9, 3],
[7.9, 3.8, 6.4, 2, 3],
[6.4, 2.8, 5.6, 2.2, 3],
[6.3, 2.8, 5.1, 1.5, 3],
[6.1, 2.6, 5.6, 1.4, 3],
[7.7, 3, 6.1, 2.3, 3],
[6.3, 3.4, 5.6, 2.4, 3],
[6.4, 3.1, 5.5, 1.8, 3],
[6, 3, 4.8, 1.8, 3],
[6.9, 3.1, 5.4, 2.1, 3],
[6.7, 3.1, 5.6, 2.4, 3],
[6.9, 3.1, 5.1, 2.3, 3],
[5.8, 2.7, 5.1, 1.9, 3],
[6.8, 3.2, 5.9, 2.3, 3],
[6.7, 3.3, 5.7, 2.5, 3],
[6.7, 3, 5.2, 2.3, 3],
[6.3, 2.5, 5, 1.9, 3],
[6.5, 3, 5.2, 2, 3],
[6.2, 3.4, 5.4, 2.3, 3],
[5.9, 3, 5.1, 1.8, 3]]

In [6]:
for i in data:
    n.train(i[0:4], i[4:5])

Inputs:
 [[ 5.1]
 [ 3.5]
 [ 1.4]
 [ 0.2]]
Targets:
 [[1]]
Hidden inputs:
 [[ 0.67904183]
 [-1.41201527]
 [-2.74912646]
 [ 2.64910125]]
Hidden outputs:
 [[ 0.66352481]
 [ 0.19591639]
 [ 0.060136  ]
 [ 0.93395557]]
Final iutputs:
 [[-0.3745718]]
Final outputs:
 [[ 0.40743678]]
Output errors:
 [[ 0.59256322]]
Output errors:
 [[-0.06660435]
 [ 0.18548045]
 [-0.22445788]
 [-0.21479019]]
Inputs:
 [[ 4.9]
 [ 3. ]
 [ 1.4]
 [ 0.2]]
Targets:
 [[1]]
Hidden inputs:
 [[ 0.33716558]
 [-0.83919299]
 [-2.8272845 ]
 [ 2.12974276]]
Hidden outputs:
 [[ 0.58350184]
 [ 0.30170478]
 [ 0.05586746]
 [ 0.89376058]]
Final iutputs:
 [[-0.224404]]
Final outputs:
 [[ 0.44413325]]
Output errors:
 [[ 0.55586675]]
Output errors:
 [[-0.03609645]
 [ 0.18178402]
 [-0.20816644]
 [-0.16435246]]
Inputs:
 [[ 4.7]
 [ 3.2]
 [ 1.3]
 [ 0.2]]
Targets:
 [[1]]
Hidden inputs:
 [[ 0.18711841]
 [-0.10470256]
 [-2.94865969]
 [ 1.91594169]]
Hidden outputs:
 [[ 0.54664359]
 [ 0.47384825]
 [ 0.0497999 ]
 [ 0.8716852 ]]
Final iutputs:
 [[

 [[ 0.14785484]]
Output errors:
 [[ 0.07063198]
 [ 0.14275658]
 [-0.05207198]
 [ 0.0532533 ]]
Inputs:
 [[ 4.7]
 [ 3.2]
 [ 1.6]
 [ 0.2]]
Targets:
 [[1]]
Hidden inputs:
 [[ 2.98895117]
 [ 4.31050826]
 [-4.07179401]
 [ 2.73934588]]
Hidden outputs:
 [[ 0.95207247]
 [ 0.98675116]
 [ 0.01676106]
 [ 0.93930882]]
Final iutputs:
 [[ 1.76587158]]
Final outputs:
 [[ 0.85394351]]
Output errors:
 [[ 0.14605649]]
Output errors:
 [[ 0.07108567]
 [ 0.14236461]
 [-0.05142202]
 [ 0.05389254]]
Inputs:
 [[ 4.8]
 [ 3.1]
 [ 1.6]
 [ 0.2]]
Targets:
 [[1]]
Hidden inputs:
 [[ 3.07367469]
 [ 4.3074356 ]
 [-4.11987094]
 [ 2.76299601]]
Hidden outputs:
 [[ 0.9557937 ]
 [ 0.98671093]
 [ 0.01598688]
 [ 0.94064313]]
Final iutputs:
 [[ 1.79361532]]
Final outputs:
 [[ 0.85736995]]
Output errors:
 [[ 0.14263005]]
Output errors:
 [[ 0.07065489]
 [ 0.14030669]
 [-0.0501939 ]
 [ 0.05384852]]
Inputs:
 [[ 5.4]
 [ 3.4]
 [ 1.5]
 [ 0.4]]
Targets:
 [[1]]
Hidden inputs:
 [[ 3.47610868]
 [ 4.59086811]
 [-4.5013798 ]
 [ 3.09064083]]

Final iutputs:
 [[ 4.96928853]]
Final outputs:
 [[ 0.99309985]]
Output errors:
 [[ 2.00690015]]
Output errors:
 [[ 3.07311999]
 [ 4.06491993]
 [-0.69712691]
 [ 2.8356449 ]]
Inputs:
 [[ 5.6]
 [ 2.8]
 [ 4.9]
 [ 2. ]]
Targets:
 [[3]]
Hidden inputs:
 [[ 7.7093203 ]
 [ 8.64043267]
 [-6.69827987]
 [ 8.0674629 ]]
Hidden outputs:
 [[ 0.99955157]
 [ 0.99982322]
 [ 0.00123151]
 [ 0.99968652]]
Final iutputs:
 [[ 4.98840192]]
Final outputs:
 [[ 0.9932296]]
Output errors:
 [[ 2.0067704]]
Output errors:
 [[ 3.08671903]
 [ 4.07845553]
 [-0.69707762]
 [ 2.84925953]]
Inputs:
 [[ 7.7]
 [ 2.8]
 [ 6.7]
 [ 2. ]]
Targets:
 [[3]]
Hidden inputs:
 [[ 10.35215143]
 [ 11.24736468]
 [ -9.08154353]
 [ 10.26033766]]
Hidden outputs:
 [[  9.99968077e-01]
 [  9.99986959e-01]
 [  1.13732965e-04]
 [  9.99965007e-01]]
Final iutputs:
 [[ 5.01039411]]
Final outputs:
 [[ 0.9933759]]
Output errors:
 [[ 2.0066241]]
Output errors:
 [[ 3.10002728]
 [ 4.09169516]
 [-0.69701013]
 [ 2.86258692]]
Inputs:
 [[ 6.3]
 [ 2.7]
 [ 4.9]
 [

In [6]:
n.query([6.3, 2.5, 5, 1.9])

Inputs:
 [[ 6.3]
 [ 2.5]
 [ 5. ]
 [ 1.9]]
Hidden inputs:
 [[ 2.55710277]
 [ 1.79916485]
 [ 4.02119218]
 [-1.00173161]]
Hidden outputs:
 [[ 0.92804924]
 [ 0.85804724]
 [ 0.9823843 ]
 [ 0.2686011 ]]
Final iutputs:
 [[-0.04240389]]
Final outputs:
 [[ 0.48940062]]


array([[ 0.48940062]])